# Generated by Django 2.1.5 on 2019-01-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilogram', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumnail_image',
        ),
        migrations.AddField(
            model_name='photo',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
