# Generated by Django 2.1.5 on 2019-01-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pu_data',
            new_name='pub_date',
        ),
    ]
